# SwiftLint Configuration
# More lenient rules for test files

disabled_rules:
  - trailing_whitespace

excluded:
  - Pods
  - DerivedData
  - .build

# Rule configuration
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true
  
function_body_length:
  warning: 75
  error: 150

type_body_length:
  warning: 600
  error: 800

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60

analyzer_rules:
  - unused_import