workflows:
  ios-native-workflow:
    name: PokedexPocket iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    environment:
      vars:
        XCODE_PROJECT: "PokedexPocket.xcodeproj"
        XCODE_SCHEME: "PokedexPocket"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: | 
          echo "Installing dependencies..."
          # Install xcpretty for better test output formatting
          gem install xcpretty
          # Create reports directory
          mkdir -p reports
          # Resolve Swift Package Manager dependencies
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT"
          
      - name: Run SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            echo "Running SwiftLint..."
            swiftlint lint --quiet
          else
            echo "SwiftLint not found, installing..."
            brew install swiftlint
            swiftlint lint --quiet
          fi
          
      - name: Run tests
        script: |
          echo "Running tests..."
          xcodebuild test \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
            -only-testing:PokedexPocketTests \
            -skipPackagePluginValidation \
            -resultBundlePath TestResults \
            | xcpretty --report junit --output reports/junit.xml --report html --output reports/index.html
            
      - name: Build for simulator (no signing required)
        script: | 
          echo "Building for iOS Simulator..."
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
            -configuration Debug \
            -skipPackagePluginValidation
            
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - TestResults/
      - reports/
      
    publishing:
      # Email notifications
      email:
        recipients:
          - muhammad.azri.f.s@gmail.com
        notify:
          success: true
          failure: true